=== n4feng/rag_conformal_pred/data/out/subclaims_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "query": {
        "type": "string",
        "description": "The question string."
      },
      "gld_ans": {
        "type": "string",
        "description": "The golden answer."
      },
      "response": {
        "type": "string",
        "description": "LLM-generated response."
      },
      "subclaims": {
        "type": "array",
        "description": "Array of subclaims related to the response.",
        "items": {
          "type": "object",
          "properties": {
            "subclaim": {
              "type": "string",
              "description": "one subclaim string."
            },
            "scores": {
              "type": "array",
              "description": "Optional list of scores associated with the subclaim.",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "The type of score."
                  },
                  "score": {
                    "type": "number",
                    "description": "The score as a float."
                  }
                },
                "required": ["type", "score"]
              },
              "optional": true
            },
            "annotations": {
              "type": "array",
              "description": "Optional list of annotations associated with the subclaim.",
              "items": {
                "type": "object",
                "properties": {
                  "type": {
                    "type": "string",
                    "description": "The type of annotation."
                  },
                  "annotation": {
                    "type": "string",
                    "description": "The annotation text."
                  }
                },
                "required": ["type", "annotation"]
              },
              "optional": true
            }
          },
          "required": ["subclaim"]
        }
      }
    },
    "required": ["query", "gld_ans", "response"]
  }

=== n4feng/rag_conformal_pred/data/out/FactScore/factscore_subclaims.json
[
    {
        "query": "What is Lanny Flaherty's occupation?",
        "gld_ans": "",
        "response": "Lanny Flaherty is an American actor.",
        "subclaims": [
            {
                "subclaim": "Lanny Flaherty is an American actor:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.45577080222368244
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            }
        ]
    },
    {
        "query": "What is Marianne McAndrew's occupation?",
        "gld_ans": "",
        "response": "Marianne McAndrew is an actress, known for her role as Irene Molloy in the film \"Hello, Dolly!\"",
        "subclaims": [
            {
                "subclaim": "Marianne McAndrew is an actress: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.3698780537605286
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Marianne McAndrew is known for her role as Irene Molloy in the film \"Hello, Dolly!\": supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.4305130900859833
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " The film \"Hello, Dolly!\" features a character named Irene Molloy: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.3166929779052734
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            }
        ]
    },
    {
        "query": "What is Chaim Malinowitz's occupation?",
        "gld_ans": "",
        "response": "Chaim Malinowitz was a Haredi community rabbi, a dayan (rabbinical court judge), and a Talmudic scholar. He was also the general editor of the Schottenstein Edition of the Babylonian Talmud published by ArtScroll. After immigrating to Israel, he served as the rabbi of Beis Tefillah Yonah Avraham in Ramat Beit Shemesh.",
        "subclaims": [
            {
                "subclaim": "Chaim Malinowitz was a Haredi community rabbi:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.4906873934268951
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Chaim Malinowitz was a dayan (rabbinical court judge):supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.5217339384555817
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Chaim Malinowitz was a Talmudic scholar:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.531123052239418
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Chaim Malinowitz was the general editor of the Schottenstein Edition of the Babylonian Talmud published by ArtScroll:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.46746852722167964
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Chaim Malinowitz immigrated to Israel:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.45645819454193115
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Chaim Malinowitz served as the rabbi of Beis Tefillah Yonah Avraham in Ramat Beit Shemesh:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.4546292264699936
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            }
        ]
    },
    {
        "query": "What is Doug Sheehan's occupation?",
        "gld_ans": "",
        "response": "Doug Sheehan is an American actor. He is known for his roles in television series such as \"Knots Landing\" and \"General Hospital.\"",
        "subclaims": [
            {
                "subclaim": "Dug Sheehan is an American actor:supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.295687776735425
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Doug Sheehan is known for his roles in television series such as \"Knots Landing\":supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.40001752287149434
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Doug Sheehan is known for his roles in television series such as \"General Hospital\":supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.35760944112539295
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            }
        ]
    },
    {
        "query": "What is Gerhard Fischer (inventor)'s occupation?",
        "gld_ans": "",
        "response": "Gerhard Fischer was an entrepreneur and inventor, specifically known for contributing to the development and popularization of the handheld metal detector. He founded Fisher Research Laboratory, Inc. in 1931 and served as its president until his retirement in 1967.",
        "subclaims": [
            {
                "subclaim": "Gerhard Fischer was an entrepreneur and inventor: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.4505252458691597
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Gerhard Fischer contributed to the development and popularization of the handheld metal detector: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.49430298643112186
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Gerhard Fischer founded Fisher Research Laboratory, Inc. in 1931: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.447712082695961
                    }
                ],
                "annotations": [
                    {
                        "type": "gpt",
                        "annotation": "S"
                    }
                ]
            },
            {
                "subclaim": " Gerhard Fischer served as president of Fisher Research Laboratory, Inc. until his retirement in 1967: supported",
                "scores": [
                    {
                        "type": "similarity",
                        "score": 0.41955047851204874
                    }
                ],
                "annotations": [
                    {
